### ISSUE TITLE
Examples and learning by doing

### ISSUE THREAD

**Issue by j-i-l** [t4d-gmbh/working-with-git#25]
https://github.com/t4d-gmbh/using-git-in-academia/blob/ffb0b0ca004ac04f2f4491d15d01b5ce4484418b/README.md?plain=1#L33C1-L33C130

---

# To Do

This part is not yet represented in https://github.com/t4d-gmbh/working-with-git, but we should add a section 'Exercise' with the below instructions:

We wanted to keep this strictly command line, so we would add instructions to

- clone a (almost) barebone repo (we can still use the [Weekend Out](https://github.com/t4d-gmbh/Weekend-Out) just at a minimal version)
- instruct to create a feature branch for some feature (to determine)
- checkout how one can do edits on the remove (in the `main` branch such that we introduce changes before the feature branch is merged
- instruct to merge the feature branch
- realize the conflict and resolve it (locally)
- push 
- check the resulting history (provide a visual representation as comparison)

**Comment by matteodelucchi** [comment]
add the exercises after this section in the course: https://t4d-gmbh.github.io/using-git-in-academia/content/working-with-git/source/content/update_cycle/index.html
