### ISSUE TITLE
Slides don't render `history.md`

### ISSUE THREAD

**Issue by matteodelucchi** [t4d-gmbh/working-with-git#29]
For some reason, the file [`history.md`](https://github.com/t4d-gmbh/working-with-git/pull/28/files#diff-f8c91356eff453f0fe366816f614c8220f8e10e2bc8a41aaf36d4a55298b6cba) appears only in the page view mode. @j-i-l any idea? Relates to #28

**Comment by j-i-l** [comment]
Hm, with 76aa0b9aad7674e70 I get this slide:

![2024-10-15T15:27:51,763173745+02:00](https://github.com/user-attachments/assets/84c44063-75bc-49cc-9e75-21c93fa34ecf)

That is OK, no?

**Comment by j-i-l** [comment]
A browser caching issue maybe? :confused:
